### PR TITLE
Added a 'indicators' option similar to the bootstrap carousel

### PR DESCRIPTION
**Pull request by rhertogh**
'indicators' option can be set in global and in step options. See demo step in docs or  http://prntscr.com/7qe2xt

### CODE REVIEW

**Comment by rhertogh** [comment]
Somehow the test process crashes at random points (I had the same problem locally), but sometimes it's passing.

**Comment by sorich87** [comment]
@rhertogh noticed that. no worries :)

**Comment by rhertogh** [comment]
Hi Sorich, any update on this one?

**Comment by sorich87** [comment]
I'm wondering if there's a better way to handle the indicators template. Cc @ousram @brexis

**Comment by rhertogh** [comment]
There might be. It's a while ago, but I think I did it this way so that it's fully backward compatible.

**Comment by RishiChowdaryPentyala** [comment]
Is this feature added to bootstrap tour?

**Review by shaischaudhry — APPROVED** [review]

**Pull request closed without merging**
