### PR TITLE
Add ability to set a container for the backdrop.

### PR DESCRIPTION
**Pull request by mrobinet**
This adds the ability to control where the backdrop and overlay are injected into the page. The backdrop does not behave properly if the target element of the step is in a different [stacking context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context).

One example in bootstrap would be navbar links: http://jsfiddle.net/qpolarbear/8qqpkcgn/6/

This change allows you to place the backdrop inside the same stacking context as the step element.

### CODE REVIEW

**Comment by klmdb** [comment]
any updates on this?

**Comment by Cruig** [comment]
I'd also appreciate this functionality - can't use the backdrop feature otherwise because of the stacking context.

**Comment by bnussey** [comment]
hey @mrobinet  any updates on this? would love to use this!

**Comment by mrobinet** [comment]
Originally when I opened this request it was failing on some random error. Checking again it was a legit test failure. I think I've fixed that, but I did merge latest and it looks like master is failing, so will probably have to merge in again once master is fixed.

**Comment by sorich87** [comment]
Thanks @mrobinet !

**Comment by mrobinet** [comment]
Thanks for merging this!

**Comment by bnussey** [comment]
Thanks @mrobinet & @sorich87  is this ready to go now?

**Comment by malnosna** [comment]
Just wondering if there is any update to this issue?

**Comment by sorich87** [comment]
It has been merged with master and will be released in the next version. You can use the code from master in the meantime.

**Comment by malnosna** [comment]
I just tried the code from master. I added backdropContainer: "#somediv" within the steps, but in some scenarios it "highlight" more regions than intended. It also lost the round corners in the "highlighted" region. Am I doing it right?

**Comment by chrisvidal** [comment]
i just tried to use the new backdropContainer, but the rendering is random, i still loose some styling here and there. Is there any documentation about how to use / place this backdropContainer properly ?

**Comment by mrobinet** [comment]
@chrisvidal Managing stacking contexts can be tricky and other styles you have applied to the related elements may be causing issues. Can you distill the problem in a jsfiddle?

**Comment by malnosna** [comment]
In your bootstrap navbar example, what would you define as the backdropContainer, and how did you do it in the code?

**Comment by malnosna** [comment]
Is it just me, or backdropPadding does not work with backdropContainer?

**Comment by vkovalskiy** [comment]
Working around stacking issues could be a real pain.. Probably it's better to create a 'wholed' backdrop on the body level so that it would consist of the 4 rectangles with a whole ? Haven't anybody tested / implemented this approach?

**Pull request merged**
