### PR TITLE
Add support for the AMD loader

### PR DESCRIPTION
**Pull request by andrewnicols**
I'd quite like to use this library in a project I work on (moodle/moodle), however JS in Moodle is loaded via AMD/requireJS.

This patch adds support for requireJS by modifying the way in which it is loaded.

I'm afraid I don't quite know where to start with adding appropriate tests for this, but existing tests continue to pass.
I have also only submitted the coffee file and not the built files. Hope this is correct.

### CODE REVIEW

**Comment by sorich87** [comment]
Merged with some modifications in 57ee74898b17754e1119c0dab75a1d1151e1dd2a.

@andrewnicols how is the integration with Moodle going? anywhere I can follow it?

**Comment by andrewnicols** [comment]
Hi,

I've created a plugin for the tours which applies to Moodle 3.0, and 3.1.

We hope to get this into Moodle 3.2 core, but currently face a number of issues with accessibility which we intend to feed back here.

At some point we will be looking to move to Bootstrap 4 too.

**Comment by sorich87** [comment]
Thanks @andrewnicols. Can't wait to read your feedback about accessibility!

**Comment by sorich87** [comment]
There's a discussion about Bootstrap 4 here https://github.com/sorich87/bootstrap-tour/issues/554.

**Pull request closed without merging**
